apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "beyla.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  beyla-config.yml: |
    print_traces: true
    grafana:
      otlp:
        submit: ["metrics","traces"]
    otel_traces_export:
      sampler:
        name: parentbased_traceidratio
        arg: "0.01"
    routes:
      patterns:
        - /factorial/{num}
